const books = [ { author: 'Вордерман Кэрол',
    pic: 'https://img2.labirint.ru/books49/481230/covermid.png',
    title: 'Программирование для детей. Иллюстрированное руководство по языкам Scratch и Python',
    year: 2015 },
    { author: 'Бриггс Джейсон',
        pic: 'https://img2.labirint.ru/books58/575392/covermid.png',
        title: 'Python для детей. Самоучитель по программированию',
        year: 2007 },
    { author: 'Лааксонен Антти',
        pic: 'https://img1.labirint.ru/books65/649871/covermid.jpg',
        title: 'Олимпиадное программирование',
        year: 2013 },
    { author: 'Морган Ник',
        pic: 'https://img2.labirint.ru/books56/551756/covermid.png',
        title: 'JavaScript для детей. Самоучитель по программированию',
        year: 2004 },
    { author: 'Воронин Игорь',
        pic: 'https://img2.labirint.ru/books66/656408/covermid.jpg',
        title: 'Программирование для детей. От основ к созданию роботов',
        year: 2003 },
    { author: 'Бэрри Пол',
        pic: 'https://img1.labirint.ru/books61/601607/covermid.jpg',
        title: 'Изучаем программирование на Python',
        year: 2010 },
    { author: 'Клеппман Мартин',
        pic: 'https://img1.labirint.ru/books64/632959/covermid.jpg',
        title: 'Высоконагруженные приложения. Программирование, масштабирование, поддержка',
        year: 2009 },
    { author: 'Кнут Дональд Эрвин',
        pic: 'https://img1.labirint.ru/books52/512935/covermid.jpg',
        title: 'Искусство программирования. Том 1. Основные алгоритмы',
        year: 2004 },
    { author: 'Вордерман Кэрол',
        pic: 'https://img1.labirint.ru/books64/637513/covermid.png',
        title: 'Программирование на Python. Иллюстрированное руководство для детей',
        year: 2017 },
    { author: 'Кнут Дональд Эрвин',
        pic: 'https://img1.labirint.ru/books52/512973/covermid.jpg',
        title: 'Искусство программирования. Том 4А. Комбинаторные алгоритмы. Часть 1',
        year: 2005 },
    { author: 'Стивенс У. Ричард',
        pic: 'https://img2.labirint.ru/books63/627666/covermid.jpg',
        title: 'UNIX. Профессиональное программирование',
        year: 2004 },
    { author: 'Фримен Эрик',
        pic: 'https://img2.labirint.ru/books48/473786/covermid.jpg',
        title: 'Изучаем программирование на JavaScript',
        year: 2005 },
    { author: 'Блэнди Джим',
        pic: 'https://img1.labirint.ru/books64/630003/covermid.jpg',
        title: 'Программирование на языке Rust. Цветное издание',
        year: 2015 },
    { author: 'Рихтер Джеффри',
        pic: 'https://img1.labirint.ru/books41/401209/covermid.jpg',
        title: 'CLR via C#. Программирование на платформе MicrosoftNET Framework 4.5 на языке C#. 4-е издание',
        year: 2005 },
    { author: 'Троелсен Эндрю',
        pic: 'https://img2.labirint.ru/books56/550458/covermid.jpg',
        title: 'Язык программирования C# 6.0 и платформаNET 4.6',
        year: 2015 },
    { author: 'Прата Стивен',
        pic: 'https://img2.labirint.ru/books52/512980/covermid.jpg',
        title: 'Язык программирования C++. Лекции и упражнения',
        year: 2008 },
    { author: 'Страуструп Бьярне',
        pic: 'https://img2.labirint.ru/books52/512976/covermid.jpg',
        title: 'Программирование. Принципы и практика с использованием C++',
        year: 2006 },
    { author: 'Гриффитс Дэвид',
        pic: 'https://img1.labirint.ru/books65/640423/covermid.jpg',
        title: 'Head First. Программирование для Android',
        year: 2012 },
    { author: 'Седжвик Роберт',
        pic: 'https://img2.labirint.ru/books64/633862/covermid.jpg',
        title: 'Computer Science. Основы программирования на Java, ООП, алгоритмы и структуры данных',
        year: 2001 },
    { author: 'Любанович Билл',
        pic: 'https://img2.labirint.ru/books55/546688/covermid.jpg',
        title: 'Простой Python. Современный стиль программирования',
        year: 2004 },
    { author: 'Зандстра Мэтт',
        pic: 'https://img1.labirint.ru/books52/512925/covermid.jpg',
        title: 'PHP. Объекты, шаблоны и методики программирования',
        year: 2012 },
    { author: 'Дашнер Себастьян',
        pic: 'https://img1.labirint.ru/books66/651967/covermid.jpg',
        title: 'Изучаем Java EE. Современное программирование для больших предприятий',
        year: 2009 },
    { author: 'Филлипс Билл',
        pic: 'https://img2.labirint.ru/books60/596118/covermid.jpg',
        title: 'Android. Программирование для профессионалов',
        year: 2007 },
    { author: 'Уокенбах Джон',
        pic: 'https://img2.labirint.ru/books52/513024/covermid.jpg',
        title: 'Excel 2013. Профессиональное программирование на VBA',
        year: 2007 },
    { author: 'Прата Стивен',
        pic: 'https://img1.labirint.ru/books52/512951/covermid.jpg',
        title: 'Язык программирования C. Лекции и упражнения',
        year: 2016 },
    { author: 'Лафоре Роберт',
        pic: 'https://img1.labirint.ru/books25/249955/covermid.jpg',
        title: 'Объектно-ориентированное программирование в С++',
        year: 2016 },
    { author: 'Шлее Макс',
        pic: 'https://img1.labirint.ru/books64/635501/covermid.jpg',
        title: 'Qt 5.10. Профессиональное программирование на C++',
        year: 2009 },
    { author: 'Бек Кент',
        pic: 'https://img2.labirint.ru/books59/583040/covermid.jpg',
        title: 'Экстремальное программирование. Разработка через тестирование',
        year: 2005 },
    { author: 'Мак-Локлин Майкл',
        pic: 'https://img1.labirint.ru/books58/577007/covermid.jpg',
        title: 'Oracle Database 11g. Программирование на языке PL/SQL',
        year: 2008 },
    { author: 'Маржи Мажед',
        pic: 'https://img2.labirint.ru/books57/563662/covermid.png',
        title: 'Scratch для детей. Самоучитель по программированию',
        year: 2014 },
    { author: 'Керниган Брайан',
        pic: 'https://img2.labirint.ru/books52/512950/covermid.jpg',
        title: 'Язык программирования C',
        year: 2008 },
    { author: 'Страуструп Бьерн',
        pic: 'https://img2.labirint.ru/books31/300232/covermid.jpg',
        title: 'Язык программирования C++. Специальное издание',
        year: 2012 },
    { author: 'Хорстманн Кей С.',
        pic: 'https://img1.labirint.ru/books61/603633/covermid.jpg',
        title: 'Java. Библиотека профессионала. Том 2. Расширенные средства программирования',
        year: 2013 },
    { author: 'Васильев А. Н.',
        pic: 'https://img1.labirint.ru/books59/588691/covermid.jpg',
        title: 'Python на примерах. Практический курс по программированию',
        year: 2003 },
    { author: 'Седжвик Роберт',
        pic: 'https://img2.labirint.ru/books56/558936/covermid.jpg',
        title: 'Программирование на языке Python. Учебный курс',
        year: 2004 },
    { author: 'Мэтиз Эрик',
        pic: 'https://img1.labirint.ru/books60/593039/covermid.jpg',
        title: 'Изучаем Python. Программирование игр, визуализация данных, веб-приложения',
        year: 2007 },
    { author: 'Иерузалимски Роберту',
        pic: 'https://img2.labirint.ru/books44/433606/covermid.jpg',
        title: 'Программирование на языке Lua',
        year: 2007 },
    { author: 'Коузен Кен',
        pic: 'https://img2.labirint.ru/books64/638778/covermid.jpg',
        title: 'Современный Java. Рецепты программирования',
        year: 2001 },
    { author: 'Радовель Валентина Александровна',
        pic: 'https://img1.labirint.ru/books64/632481/covermid.jpg',
        title: 'Английский язык в программировании и информационных системах (СПО). Учебник',
        year: 2010 },
    { author: 'Уитни Дэвид',
        pic: 'https://img1.labirint.ru/books63/621937/covermid.jpg',
        title: 'Программирование для детей. Учимся создавать сайты, приложения и игры. HTML, CSS и JavaScript',
        year: 2008 },
    { author: 'Атенсио Луис',
        pic: 'https://img1.labirint.ru/books63/620557/covermid.jpg',
        title: 'Функциональное программирование на JavaScript. Как улучшить код JavaScript-программ',
        year: 2003 },
    { author: 'Свейгарт Эл',
        pic: 'https://img2.labirint.ru/books62/614370/covermid.jpg',
        title: 'Программирование для детей. Делай игры и учи язык Scratch!',
        year: 2012 },
    { author: 'Скит Джон',
        pic: 'https://img1.labirint.ru/books52/512895/covermid.jpg',
        title: 'C# для профессионалов. Тонкости программирования',
        year: 2014 },
    { author: 'Скляр Дэвид',
        pic: 'https://img2.labirint.ru/books48/478996/covermid.jpg',
        title: 'PHP. Рецепты программирования',
        year: 2001 },
    { author: 'Уильямс Энтони',
        pic: 'https://img1.labirint.ru/books44/433609/covermid.jpg',
        title: 'Параллельное программирование на С++ в действии. Практика разработки многопоточных программ',
        year: 2003 },
    { author: 'Павловская Татьяна Александровна',
        pic: 'https://img2.labirint.ru/books65/641482/covermid.jpg',
        title: 'C/C++. Процедурное и объектно-ориентированное программирование. Учебник для вузов',
        year: 2005 },
    { author: 'Антонопулос Андреас М.',
        pic: 'https://img2.labirint.ru/books65/640434/covermid.jpg',
        title: 'Осваиваем биткойн. Программирование блокчейна',
        year: 2009 },
    { author: 'Тюкачев Николай Аркадьевич',
        pic: 'https://img2.labirint.ru/books60/598758/covermid.jpg',
        title: 'C#. Основы программирования (+CD). Учебное пособие',
        year: 2001 },
    { author: 'Златопольский Дмитрий Михайлович',
        pic: 'https://img2.labirint.ru/books62/616374/covermid.jpg',
        title: 'Подготовка к ЕГЭ по информатике. Решение задач по программированию',
        year: 2005 },
    { author: 'Керниган Брайан',
        pic: 'https://img1.labirint.ru/books52/518955/covermid.jpg',
        title: 'Практика программирования',
        year: 2007 },
    { author: 'Такахаши Манна',
        pic: 'https://img1.labirint.ru/books44/438233/covermid.jpg',
        title: 'Занимательное программирование. Базы данных',
        year: 2009 },
    { author: 'Гриффитс Иэн',
        pic: 'https://img2.labirint.ru/books44/433292/covermid.jpg',
        title: 'Программирование на C# 5.0',
        year: 2011 },
    { author: 'Торгашева Юлия Владимировна',
        pic: 'https://img2.labirint.ru/books65/641492/covermid.jpg',
        title: 'Программирование для детей. Учимся создавать игры на Scratch',
        year: 2006 },
    { author: 'Томашевский П. Р.',
        pic: 'https://img1.labirint.ru/books63/622649/covermid.jpg',
        title: 'Привет, Python! Моя первая книга по программированию',
        year: 2007 },
    { author: 'Вагнер Билл',
        pic: 'https://img2.labirint.ru/books63/620556/covermid.jpg',
        title: 'Наиболее эффективное программирование на C#. 50 способов улучшения кода',
        year: 2001 },
    { author: 'Одерски Мартин',
        pic: 'https://img1.labirint.ru/books62/617527/covermid.jpg',
        title: 'Scala. Профессиональное программирование',
        year: 2004 },
    { author: 'Степанов Александр Александрович',
        pic: 'https://img2.labirint.ru/books61/603634/covermid.jpg',
        title: 'Начала программирования',
        year: 2009 },
    { author: 'Орлов Сергей Александрович',
        pic: 'https://img2.labirint.ru/books60/595914/covermid.jpg',
        title: 'Теория и практика языков программирования. Учебник',
        year: 2012 },
    { author: 'Васильев А. Н.',
        pic: 'https://img1.labirint.ru/books55/543479/covermid.jpg',
        title: 'Объектно-ориентированное программирование на C++',
        year: 2001 },
    { author: 'Саммерфильд Марк',
        pic: 'https://img2.labirint.ru/books38/376836/covermid.jpg',
        title: 'Программирование на языке Go. Разработка приложений XXI века',
        year: 2014 } ];